
#ifndef sodium_H
#define sodium_H

#include "include/version.h"

#include "include/core.h"
#include "include/crypto_aead_aes256gcm.h"
#include "include/crypto_aead_chacha20poly1305.h"
#include "include/crypto_aead_xchacha20poly1305.h"
#include "include/crypto_auth.h"
#include "include/crypto_auth_hmacsha256.h"
#include "include/crypto_auth_hmacsha512.h"
#include "include/crypto_auth_hmacsha512256.h"
#include "include/crypto_box.h"
#include "include/crypto_box_curve25519xsalsa20poly1305.h"
#include "include/crypto_core_hsalsa20.h"
#include "include/crypto_core_hchacha20.h"
#include "include/crypto_core_salsa20.h"
#include "include/crypto_core_salsa2012.h"
#include "include/crypto_core_salsa208.h"
#include "include/crypto_generichash.h"
#include "include/crypto_generichash_blake2b.h"
#include "include/crypto_hash.h"
#include "include/crypto_hash_sha256.h"
#include "include/crypto_hash_sha512.h"
#include "include/crypto_kdf.h"
#include "include/crypto_kdf_blake2b.h"
#include "include/crypto_kx.h"
#include "include/crypto_onetimeauth.h"
#include "include/crypto_onetimeauth_poly1305.h"
#include "include/crypto_pwhash.h"
#include "include/crypto_pwhash_argon2i.h"
#include "include/crypto_scalarmult.h"
#include "include/crypto_scalarmult_curve25519.h"
#include "include/crypto_secretbox.h"
#include "include/crypto_secretbox_xsalsa20poly1305.h"
#include "include/crypto_secretstream_xchacha20poly1305.h"
#include "include/crypto_shorthash.h"
#include "include/crypto_shorthash_siphash24.h"
#include "include/crypto_sign.h"
#include "include/crypto_sign_ed25519.h"
#include "include/crypto_stream.h"
#include "include/crypto_stream_chacha20.h"
#include "include/crypto_stream_salsa20.h"
#include "include/crypto_stream_xsalsa20.h"
#include "include/crypto_verify_16.h"
#include "include/crypto_verify_32.h"
#include "include/crypto_verify_64.h"
#include "include/randombytes.h"
#ifdef __native_client__
# include "include/randombytes_nativeclient.h"
#endif
#include "include/randombytes_salsa20_random.h"
#include "include/randombytes_sysrandom.h"
#include "include/runtime.h"
#include "include/utils.h"

#ifndef SODIUM_LIBRARY_MINIMAL
# include "include/crypto_box_curve25519xchacha20poly1305.h"
# include "include/crypto_core_ed25519.h"
# include "include/crypto_scalarmult_ed25519.h"
# include "include/crypto_secretbox_xchacha20poly1305.h"
# include "include/crypto_pwhash_scryptsalsa208sha256.h"
# include "include/crypto_stream_salsa2012.h"
# include "include/crypto_stream_salsa208.h"
# include "include/crypto_stream_xchacha20.h"
#endif

#endif
