// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package sodium

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error int32

const (
	Error_ERROR_UNKNOWN             Error = 0
	Error_ERROR_OPERATION_FAILED    Error = 1
	Error_ERROR_READ_REQUEST_FAILED Error = 2
)

var Error_name = map[int32]string{
	0: "ERROR_UNKNOWN",
	1: "ERROR_OPERATION_FAILED",
	2: "ERROR_READ_REQUEST_FAILED",
}
var Error_value = map[string]int32{
	"ERROR_UNKNOWN":             0,
	"ERROR_OPERATION_FAILED":    1,
	"ERROR_READ_REQUEST_FAILED": 2,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{0}
}

type KeyPair struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	SecretKey            []byte   `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPair) Reset()         { *m = KeyPair{} }
func (m *KeyPair) String() string { return proto.CompactTextString(m) }
func (*KeyPair) ProtoMessage()    {}
func (*KeyPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{0}
}
func (m *KeyPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPair.Unmarshal(m, b)
}
func (m *KeyPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPair.Marshal(b, m, deterministic)
}
func (dst *KeyPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPair.Merge(dst, src)
}
func (m *KeyPair) XXX_Size() int {
	return xxx_messageInfo_KeyPair.Size(m)
}
func (m *KeyPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPair proto.InternalMessageInfo

func (m *KeyPair) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *KeyPair) GetSecretKey() []byte {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

type SignKeyPairGenerateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignKeyPairGenerateRequest) Reset()         { *m = SignKeyPairGenerateRequest{} }
func (m *SignKeyPairGenerateRequest) String() string { return proto.CompactTextString(m) }
func (*SignKeyPairGenerateRequest) ProtoMessage()    {}
func (*SignKeyPairGenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{1}
}
func (m *SignKeyPairGenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignKeyPairGenerateRequest.Unmarshal(m, b)
}
func (m *SignKeyPairGenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignKeyPairGenerateRequest.Marshal(b, m, deterministic)
}
func (dst *SignKeyPairGenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignKeyPairGenerateRequest.Merge(dst, src)
}
func (m *SignKeyPairGenerateRequest) XXX_Size() int {
	return xxx_messageInfo_SignKeyPairGenerateRequest.Size(m)
}
func (m *SignKeyPairGenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignKeyPairGenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignKeyPairGenerateRequest proto.InternalMessageInfo

type SignKeyPairGenerateResponse struct {
	KeyPair              *KeyPair `protobuf:"bytes,1,opt,name=keyPair" json:"keyPair,omitempty"`
	Error                Error    `protobuf:"varint,2,opt,name=error,enum=sodium.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignKeyPairGenerateResponse) Reset()         { *m = SignKeyPairGenerateResponse{} }
func (m *SignKeyPairGenerateResponse) String() string { return proto.CompactTextString(m) }
func (*SignKeyPairGenerateResponse) ProtoMessage()    {}
func (*SignKeyPairGenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{2}
}
func (m *SignKeyPairGenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignKeyPairGenerateResponse.Unmarshal(m, b)
}
func (m *SignKeyPairGenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignKeyPairGenerateResponse.Marshal(b, m, deterministic)
}
func (dst *SignKeyPairGenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignKeyPairGenerateResponse.Merge(dst, src)
}
func (m *SignKeyPairGenerateResponse) XXX_Size() int {
	return xxx_messageInfo_SignKeyPairGenerateResponse.Size(m)
}
func (m *SignKeyPairGenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignKeyPairGenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignKeyPairGenerateResponse proto.InternalMessageInfo

func (m *SignKeyPairGenerateResponse) GetKeyPair() *KeyPair {
	if m != nil {
		return m.KeyPair
	}
	return nil
}

func (m *SignKeyPairGenerateResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_ERROR_UNKNOWN
}

type BoxKeyPairGenerateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxKeyPairGenerateRequest) Reset()         { *m = BoxKeyPairGenerateRequest{} }
func (m *BoxKeyPairGenerateRequest) String() string { return proto.CompactTextString(m) }
func (*BoxKeyPairGenerateRequest) ProtoMessage()    {}
func (*BoxKeyPairGenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{3}
}
func (m *BoxKeyPairGenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxKeyPairGenerateRequest.Unmarshal(m, b)
}
func (m *BoxKeyPairGenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxKeyPairGenerateRequest.Marshal(b, m, deterministic)
}
func (dst *BoxKeyPairGenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxKeyPairGenerateRequest.Merge(dst, src)
}
func (m *BoxKeyPairGenerateRequest) XXX_Size() int {
	return xxx_messageInfo_BoxKeyPairGenerateRequest.Size(m)
}
func (m *BoxKeyPairGenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxKeyPairGenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoxKeyPairGenerateRequest proto.InternalMessageInfo

type BoxKeyPairGenerateResponse struct {
	KeyPair              *KeyPair `protobuf:"bytes,1,opt,name=keyPair" json:"keyPair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxKeyPairGenerateResponse) Reset()         { *m = BoxKeyPairGenerateResponse{} }
func (m *BoxKeyPairGenerateResponse) String() string { return proto.CompactTextString(m) }
func (*BoxKeyPairGenerateResponse) ProtoMessage()    {}
func (*BoxKeyPairGenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{4}
}
func (m *BoxKeyPairGenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxKeyPairGenerateResponse.Unmarshal(m, b)
}
func (m *BoxKeyPairGenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxKeyPairGenerateResponse.Marshal(b, m, deterministic)
}
func (dst *BoxKeyPairGenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxKeyPairGenerateResponse.Merge(dst, src)
}
func (m *BoxKeyPairGenerateResponse) XXX_Size() int {
	return xxx_messageInfo_BoxKeyPairGenerateResponse.Size(m)
}
func (m *BoxKeyPairGenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxKeyPairGenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoxKeyPairGenerateResponse proto.InternalMessageInfo

func (m *BoxKeyPairGenerateResponse) GetKeyPair() *KeyPair {
	if m != nil {
		return m.KeyPair
	}
	return nil
}

type SignDetachedRequest struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SecretKey            []byte   `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDetachedRequest) Reset()         { *m = SignDetachedRequest{} }
func (m *SignDetachedRequest) String() string { return proto.CompactTextString(m) }
func (*SignDetachedRequest) ProtoMessage()    {}
func (*SignDetachedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{5}
}
func (m *SignDetachedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDetachedRequest.Unmarshal(m, b)
}
func (m *SignDetachedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDetachedRequest.Marshal(b, m, deterministic)
}
func (dst *SignDetachedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDetachedRequest.Merge(dst, src)
}
func (m *SignDetachedRequest) XXX_Size() int {
	return xxx_messageInfo_SignDetachedRequest.Size(m)
}
func (m *SignDetachedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDetachedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignDetachedRequest proto.InternalMessageInfo

func (m *SignDetachedRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignDetachedRequest) GetSecretKey() []byte {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

type SignDetachedResponse struct {
	Digest               []byte   `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDetachedResponse) Reset()         { *m = SignDetachedResponse{} }
func (m *SignDetachedResponse) String() string { return proto.CompactTextString(m) }
func (*SignDetachedResponse) ProtoMessage()    {}
func (*SignDetachedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{6}
}
func (m *SignDetachedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDetachedResponse.Unmarshal(m, b)
}
func (m *SignDetachedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDetachedResponse.Marshal(b, m, deterministic)
}
func (dst *SignDetachedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDetachedResponse.Merge(dst, src)
}
func (m *SignDetachedResponse) XXX_Size() int {
	return xxx_messageInfo_SignDetachedResponse.Size(m)
}
func (m *SignDetachedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDetachedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignDetachedResponse proto.InternalMessageInfo

func (m *SignDetachedResponse) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

type SignDetachedVerifyRequest struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDetachedVerifyRequest) Reset()         { *m = SignDetachedVerifyRequest{} }
func (m *SignDetachedVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*SignDetachedVerifyRequest) ProtoMessage()    {}
func (*SignDetachedVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{7}
}
func (m *SignDetachedVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDetachedVerifyRequest.Unmarshal(m, b)
}
func (m *SignDetachedVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDetachedVerifyRequest.Marshal(b, m, deterministic)
}
func (dst *SignDetachedVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDetachedVerifyRequest.Merge(dst, src)
}
func (m *SignDetachedVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_SignDetachedVerifyRequest.Size(m)
}
func (m *SignDetachedVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDetachedVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignDetachedVerifyRequest proto.InternalMessageInfo

func (m *SignDetachedVerifyRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignDetachedVerifyRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *SignDetachedVerifyRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignDetachedVerifyResponse struct {
	SignatureMatches     bool     `protobuf:"varint,1,opt,name=signatureMatches" json:"signatureMatches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDetachedVerifyResponse) Reset()         { *m = SignDetachedVerifyResponse{} }
func (m *SignDetachedVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*SignDetachedVerifyResponse) ProtoMessage()    {}
func (*SignDetachedVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{8}
}
func (m *SignDetachedVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDetachedVerifyResponse.Unmarshal(m, b)
}
func (m *SignDetachedVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDetachedVerifyResponse.Marshal(b, m, deterministic)
}
func (dst *SignDetachedVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDetachedVerifyResponse.Merge(dst, src)
}
func (m *SignDetachedVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_SignDetachedVerifyResponse.Size(m)
}
func (m *SignDetachedVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDetachedVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignDetachedVerifyResponse proto.InternalMessageInfo

func (m *SignDetachedVerifyResponse) GetSignatureMatches() bool {
	if m != nil {
		return m.SignatureMatches
	}
	return false
}

type BoxEasyRequest struct {
	Plaintext            []byte   `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	SecretKey            []byte   `protobuf:"bytes,3,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxEasyRequest) Reset()         { *m = BoxEasyRequest{} }
func (m *BoxEasyRequest) String() string { return proto.CompactTextString(m) }
func (*BoxEasyRequest) ProtoMessage()    {}
func (*BoxEasyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{9}
}
func (m *BoxEasyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxEasyRequest.Unmarshal(m, b)
}
func (m *BoxEasyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxEasyRequest.Marshal(b, m, deterministic)
}
func (dst *BoxEasyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxEasyRequest.Merge(dst, src)
}
func (m *BoxEasyRequest) XXX_Size() int {
	return xxx_messageInfo_BoxEasyRequest.Size(m)
}
func (m *BoxEasyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxEasyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoxEasyRequest proto.InternalMessageInfo

func (m *BoxEasyRequest) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

func (m *BoxEasyRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *BoxEasyRequest) GetSecretKey() []byte {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

type BoxEasyResponse struct {
	Ciphertext           []byte   `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxEasyResponse) Reset()         { *m = BoxEasyResponse{} }
func (m *BoxEasyResponse) String() string { return proto.CompactTextString(m) }
func (*BoxEasyResponse) ProtoMessage()    {}
func (*BoxEasyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{10}
}
func (m *BoxEasyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxEasyResponse.Unmarshal(m, b)
}
func (m *BoxEasyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxEasyResponse.Marshal(b, m, deterministic)
}
func (dst *BoxEasyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxEasyResponse.Merge(dst, src)
}
func (m *BoxEasyResponse) XXX_Size() int {
	return xxx_messageInfo_BoxEasyResponse.Size(m)
}
func (m *BoxEasyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxEasyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoxEasyResponse proto.InternalMessageInfo

func (m *BoxEasyResponse) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *BoxEasyResponse) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type BoxEasyOpenRequest struct {
	Ciphertext           []byte   `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	SecretKey            []byte   `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxEasyOpenRequest) Reset()         { *m = BoxEasyOpenRequest{} }
func (m *BoxEasyOpenRequest) String() string { return proto.CompactTextString(m) }
func (*BoxEasyOpenRequest) ProtoMessage()    {}
func (*BoxEasyOpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{11}
}
func (m *BoxEasyOpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxEasyOpenRequest.Unmarshal(m, b)
}
func (m *BoxEasyOpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxEasyOpenRequest.Marshal(b, m, deterministic)
}
func (dst *BoxEasyOpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxEasyOpenRequest.Merge(dst, src)
}
func (m *BoxEasyOpenRequest) XXX_Size() int {
	return xxx_messageInfo_BoxEasyOpenRequest.Size(m)
}
func (m *BoxEasyOpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxEasyOpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoxEasyOpenRequest proto.InternalMessageInfo

func (m *BoxEasyOpenRequest) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *BoxEasyOpenRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *BoxEasyOpenRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *BoxEasyOpenRequest) GetSecretKey() []byte {
	if m != nil {
		return m.SecretKey
	}
	return nil
}

type BoxEasyOpenResponse struct {
	Plaintext            []byte   `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxEasyOpenResponse) Reset()         { *m = BoxEasyOpenResponse{} }
func (m *BoxEasyOpenResponse) String() string { return proto.CompactTextString(m) }
func (*BoxEasyOpenResponse) ProtoMessage()    {}
func (*BoxEasyOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{12}
}
func (m *BoxEasyOpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxEasyOpenResponse.Unmarshal(m, b)
}
func (m *BoxEasyOpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxEasyOpenResponse.Marshal(b, m, deterministic)
}
func (dst *BoxEasyOpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxEasyOpenResponse.Merge(dst, src)
}
func (m *BoxEasyOpenResponse) XXX_Size() int {
	return xxx_messageInfo_BoxEasyOpenResponse.Size(m)
}
func (m *BoxEasyOpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxEasyOpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoxEasyOpenResponse proto.InternalMessageInfo

func (m *BoxEasyOpenResponse) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

type BoxSealRequest struct {
	Plaintext            []byte   `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxSealRequest) Reset()         { *m = BoxSealRequest{} }
func (m *BoxSealRequest) String() string { return proto.CompactTextString(m) }
func (*BoxSealRequest) ProtoMessage()    {}
func (*BoxSealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{13}
}
func (m *BoxSealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxSealRequest.Unmarshal(m, b)
}
func (m *BoxSealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxSealRequest.Marshal(b, m, deterministic)
}
func (dst *BoxSealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxSealRequest.Merge(dst, src)
}
func (m *BoxSealRequest) XXX_Size() int {
	return xxx_messageInfo_BoxSealRequest.Size(m)
}
func (m *BoxSealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxSealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoxSealRequest proto.InternalMessageInfo

func (m *BoxSealRequest) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

func (m *BoxSealRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type BoxSealResponse struct {
	Ciphertext           []byte   `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxSealResponse) Reset()         { *m = BoxSealResponse{} }
func (m *BoxSealResponse) String() string { return proto.CompactTextString(m) }
func (*BoxSealResponse) ProtoMessage()    {}
func (*BoxSealResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{14}
}
func (m *BoxSealResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxSealResponse.Unmarshal(m, b)
}
func (m *BoxSealResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxSealResponse.Marshal(b, m, deterministic)
}
func (dst *BoxSealResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxSealResponse.Merge(dst, src)
}
func (m *BoxSealResponse) XXX_Size() int {
	return xxx_messageInfo_BoxSealResponse.Size(m)
}
func (m *BoxSealResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxSealResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoxSealResponse proto.InternalMessageInfo

func (m *BoxSealResponse) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

type BoxSealOpenRequest struct {
	Ciphertext           []byte   `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Keypair              *KeyPair `protobuf:"bytes,2,opt,name=keypair" json:"keypair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxSealOpenRequest) Reset()         { *m = BoxSealOpenRequest{} }
func (m *BoxSealOpenRequest) String() string { return proto.CompactTextString(m) }
func (*BoxSealOpenRequest) ProtoMessage()    {}
func (*BoxSealOpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{15}
}
func (m *BoxSealOpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxSealOpenRequest.Unmarshal(m, b)
}
func (m *BoxSealOpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxSealOpenRequest.Marshal(b, m, deterministic)
}
func (dst *BoxSealOpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxSealOpenRequest.Merge(dst, src)
}
func (m *BoxSealOpenRequest) XXX_Size() int {
	return xxx_messageInfo_BoxSealOpenRequest.Size(m)
}
func (m *BoxSealOpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxSealOpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BoxSealOpenRequest proto.InternalMessageInfo

func (m *BoxSealOpenRequest) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *BoxSealOpenRequest) GetKeypair() *KeyPair {
	if m != nil {
		return m.Keypair
	}
	return nil
}

type BoxSealOpenResponse struct {
	Plaintext            []byte   `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoxSealOpenResponse) Reset()         { *m = BoxSealOpenResponse{} }
func (m *BoxSealOpenResponse) String() string { return proto.CompactTextString(m) }
func (*BoxSealOpenResponse) ProtoMessage()    {}
func (*BoxSealOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{16}
}
func (m *BoxSealOpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoxSealOpenResponse.Unmarshal(m, b)
}
func (m *BoxSealOpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoxSealOpenResponse.Marshal(b, m, deterministic)
}
func (dst *BoxSealOpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoxSealOpenResponse.Merge(dst, src)
}
func (m *BoxSealOpenResponse) XXX_Size() int {
	return xxx_messageInfo_BoxSealOpenResponse.Size(m)
}
func (m *BoxSealOpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoxSealOpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoxSealOpenResponse proto.InternalMessageInfo

func (m *BoxSealOpenResponse) GetPlaintext() []byte {
	if m != nil {
		return m.Plaintext
	}
	return nil
}

type HashGenericRequest struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashGenericRequest) Reset()         { *m = HashGenericRequest{} }
func (m *HashGenericRequest) String() string { return proto.CompactTextString(m) }
func (*HashGenericRequest) ProtoMessage()    {}
func (*HashGenericRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{17}
}
func (m *HashGenericRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashGenericRequest.Unmarshal(m, b)
}
func (m *HashGenericRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashGenericRequest.Marshal(b, m, deterministic)
}
func (dst *HashGenericRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashGenericRequest.Merge(dst, src)
}
func (m *HashGenericRequest) XXX_Size() int {
	return xxx_messageInfo_HashGenericRequest.Size(m)
}
func (m *HashGenericRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashGenericRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashGenericRequest proto.InternalMessageInfo

func (m *HashGenericRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type HashGenericResponse struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashGenericResponse) Reset()         { *m = HashGenericResponse{} }
func (m *HashGenericResponse) String() string { return proto.CompactTextString(m) }
func (*HashGenericResponse) ProtoMessage()    {}
func (*HashGenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{18}
}
func (m *HashGenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashGenericResponse.Unmarshal(m, b)
}
func (m *HashGenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashGenericResponse.Marshal(b, m, deterministic)
}
func (dst *HashGenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashGenericResponse.Merge(dst, src)
}
func (m *HashGenericResponse) XXX_Size() int {
	return xxx_messageInfo_HashGenericResponse.Size(m)
}
func (m *HashGenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashGenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashGenericResponse proto.InternalMessageInfo

func (m *HashGenericResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Request struct {
	// Types that are valid to be assigned to SodiumOperation:
	//	*Request_SignKeyPairGenerateRequest
	//	*Request_BoxKeyPairGenerateRequest
	//	*Request_SignDetachedRequest
	//	*Request_SignDetachedVerifyRequest
	//	*Request_BoxEasyRequest
	//	*Request_BoxEasyOpenRequest
	//	*Request_BoxSealRequest
	//	*Request_BoxSealOpenRequest
	//	*Request_HashGenericRequest
	SodiumOperation      isRequest_SodiumOperation `protobuf_oneof:"sodium_operation"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{19}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_SodiumOperation interface {
	isRequest_SodiumOperation()
}

type Request_SignKeyPairGenerateRequest struct {
	SignKeyPairGenerateRequest *SignKeyPairGenerateRequest `protobuf:"bytes,1,opt,name=signKeyPairGenerateRequest,oneof"`
}
type Request_BoxKeyPairGenerateRequest struct {
	BoxKeyPairGenerateRequest *BoxKeyPairGenerateRequest `protobuf:"bytes,2,opt,name=boxKeyPairGenerateRequest,oneof"`
}
type Request_SignDetachedRequest struct {
	SignDetachedRequest *SignDetachedRequest `protobuf:"bytes,3,opt,name=signDetachedRequest,oneof"`
}
type Request_SignDetachedVerifyRequest struct {
	SignDetachedVerifyRequest *SignDetachedVerifyRequest `protobuf:"bytes,4,opt,name=signDetachedVerifyRequest,oneof"`
}
type Request_BoxEasyRequest struct {
	BoxEasyRequest *BoxEasyRequest `protobuf:"bytes,5,opt,name=boxEasyRequest,oneof"`
}
type Request_BoxEasyOpenRequest struct {
	BoxEasyOpenRequest *BoxEasyOpenRequest `protobuf:"bytes,6,opt,name=boxEasyOpenRequest,oneof"`
}
type Request_BoxSealRequest struct {
	BoxSealRequest *BoxSealRequest `protobuf:"bytes,7,opt,name=boxSealRequest,oneof"`
}
type Request_BoxSealOpenRequest struct {
	BoxSealOpenRequest *BoxSealOpenRequest `protobuf:"bytes,8,opt,name=boxSealOpenRequest,oneof"`
}
type Request_HashGenericRequest struct {
	HashGenericRequest *HashGenericRequest `protobuf:"bytes,9,opt,name=hashGenericRequest,oneof"`
}

func (*Request_SignKeyPairGenerateRequest) isRequest_SodiumOperation() {}
func (*Request_BoxKeyPairGenerateRequest) isRequest_SodiumOperation()  {}
func (*Request_SignDetachedRequest) isRequest_SodiumOperation()        {}
func (*Request_SignDetachedVerifyRequest) isRequest_SodiumOperation()  {}
func (*Request_BoxEasyRequest) isRequest_SodiumOperation()             {}
func (*Request_BoxEasyOpenRequest) isRequest_SodiumOperation()         {}
func (*Request_BoxSealRequest) isRequest_SodiumOperation()             {}
func (*Request_BoxSealOpenRequest) isRequest_SodiumOperation()         {}
func (*Request_HashGenericRequest) isRequest_SodiumOperation()         {}

func (m *Request) GetSodiumOperation() isRequest_SodiumOperation {
	if m != nil {
		return m.SodiumOperation
	}
	return nil
}

func (m *Request) GetSignKeyPairGenerateRequest() *SignKeyPairGenerateRequest {
	if x, ok := m.GetSodiumOperation().(*Request_SignKeyPairGenerateRequest); ok {
		return x.SignKeyPairGenerateRequest
	}
	return nil
}

func (m *Request) GetBoxKeyPairGenerateRequest() *BoxKeyPairGenerateRequest {
	if x, ok := m.GetSodiumOperation().(*Request_BoxKeyPairGenerateRequest); ok {
		return x.BoxKeyPairGenerateRequest
	}
	return nil
}

func (m *Request) GetSignDetachedRequest() *SignDetachedRequest {
	if x, ok := m.GetSodiumOperation().(*Request_SignDetachedRequest); ok {
		return x.SignDetachedRequest
	}
	return nil
}

func (m *Request) GetSignDetachedVerifyRequest() *SignDetachedVerifyRequest {
	if x, ok := m.GetSodiumOperation().(*Request_SignDetachedVerifyRequest); ok {
		return x.SignDetachedVerifyRequest
	}
	return nil
}

func (m *Request) GetBoxEasyRequest() *BoxEasyRequest {
	if x, ok := m.GetSodiumOperation().(*Request_BoxEasyRequest); ok {
		return x.BoxEasyRequest
	}
	return nil
}

func (m *Request) GetBoxEasyOpenRequest() *BoxEasyOpenRequest {
	if x, ok := m.GetSodiumOperation().(*Request_BoxEasyOpenRequest); ok {
		return x.BoxEasyOpenRequest
	}
	return nil
}

func (m *Request) GetBoxSealRequest() *BoxSealRequest {
	if x, ok := m.GetSodiumOperation().(*Request_BoxSealRequest); ok {
		return x.BoxSealRequest
	}
	return nil
}

func (m *Request) GetBoxSealOpenRequest() *BoxSealOpenRequest {
	if x, ok := m.GetSodiumOperation().(*Request_BoxSealOpenRequest); ok {
		return x.BoxSealOpenRequest
	}
	return nil
}

func (m *Request) GetHashGenericRequest() *HashGenericRequest {
	if x, ok := m.GetSodiumOperation().(*Request_HashGenericRequest); ok {
		return x.HashGenericRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_SignKeyPairGenerateRequest)(nil),
		(*Request_BoxKeyPairGenerateRequest)(nil),
		(*Request_SignDetachedRequest)(nil),
		(*Request_SignDetachedVerifyRequest)(nil),
		(*Request_BoxEasyRequest)(nil),
		(*Request_BoxEasyOpenRequest)(nil),
		(*Request_BoxSealRequest)(nil),
		(*Request_BoxSealOpenRequest)(nil),
		(*Request_HashGenericRequest)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// sodium_operation
	switch x := m.SodiumOperation.(type) {
	case *Request_SignKeyPairGenerateRequest:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignKeyPairGenerateRequest); err != nil {
			return err
		}
	case *Request_BoxKeyPairGenerateRequest:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxKeyPairGenerateRequest); err != nil {
			return err
		}
	case *Request_SignDetachedRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignDetachedRequest); err != nil {
			return err
		}
	case *Request_SignDetachedVerifyRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignDetachedVerifyRequest); err != nil {
			return err
		}
	case *Request_BoxEasyRequest:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxEasyRequest); err != nil {
			return err
		}
	case *Request_BoxEasyOpenRequest:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxEasyOpenRequest); err != nil {
			return err
		}
	case *Request_BoxSealRequest:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxSealRequest); err != nil {
			return err
		}
	case *Request_BoxSealOpenRequest:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxSealOpenRequest); err != nil {
			return err
		}
	case *Request_HashGenericRequest:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HashGenericRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.SodiumOperation has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 1: // sodium_operation.signKeyPairGenerateRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignKeyPairGenerateRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_SignKeyPairGenerateRequest{msg}
		return true, err
	case 2: // sodium_operation.boxKeyPairGenerateRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxKeyPairGenerateRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_BoxKeyPairGenerateRequest{msg}
		return true, err
	case 3: // sodium_operation.signDetachedRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignDetachedRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_SignDetachedRequest{msg}
		return true, err
	case 4: // sodium_operation.signDetachedVerifyRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignDetachedVerifyRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_SignDetachedVerifyRequest{msg}
		return true, err
	case 5: // sodium_operation.boxEasyRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxEasyRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_BoxEasyRequest{msg}
		return true, err
	case 6: // sodium_operation.boxEasyOpenRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxEasyOpenRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_BoxEasyOpenRequest{msg}
		return true, err
	case 7: // sodium_operation.boxSealRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxSealRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_BoxSealRequest{msg}
		return true, err
	case 8: // sodium_operation.boxSealOpenRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxSealOpenRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_BoxSealOpenRequest{msg}
		return true, err
	case 9: // sodium_operation.hashGenericRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HashGenericRequest)
		err := b.DecodeMessage(msg)
		m.SodiumOperation = &Request_HashGenericRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// sodium_operation
	switch x := m.SodiumOperation.(type) {
	case *Request_SignKeyPairGenerateRequest:
		s := proto.Size(x.SignKeyPairGenerateRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BoxKeyPairGenerateRequest:
		s := proto.Size(x.BoxKeyPairGenerateRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SignDetachedRequest:
		s := proto.Size(x.SignDetachedRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SignDetachedVerifyRequest:
		s := proto.Size(x.SignDetachedVerifyRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BoxEasyRequest:
		s := proto.Size(x.BoxEasyRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BoxEasyOpenRequest:
		s := proto.Size(x.BoxEasyOpenRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BoxSealRequest:
		s := proto.Size(x.BoxSealRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BoxSealOpenRequest:
		s := proto.Size(x.BoxSealOpenRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_HashGenericRequest:
		s := proto.Size(x.HashGenericRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	// Types that are valid to be assigned to SodiumResult:
	//	*Response_Error
	//	*Response_SignKeyPairGenerateResponse
	//	*Response_BoxKeyPairGenerateResponse
	//	*Response_SignDetachedResponse
	//	*Response_SignDetachedVerifyResponse
	//	*Response_BoxEasyResponse
	//	*Response_BoxEasyOpenResponse
	//	*Response_BoxSealResponse
	//	*Response_BoxSealOpenResponse
	//	*Response_HashGenericResponse
	SodiumResult         isResponse_SodiumResult `protobuf_oneof:"sodium_result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_01c5bf96341473c8, []int{20}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_SodiumResult interface {
	isResponse_SodiumResult()
}

type Response_Error struct {
	Error Error `protobuf:"varint,1,opt,name=error,enum=sodium.Error,oneof"`
}
type Response_SignKeyPairGenerateResponse struct {
	SignKeyPairGenerateResponse *SignKeyPairGenerateResponse `protobuf:"bytes,2,opt,name=signKeyPairGenerateResponse,oneof"`
}
type Response_BoxKeyPairGenerateResponse struct {
	BoxKeyPairGenerateResponse *BoxKeyPairGenerateResponse `protobuf:"bytes,3,opt,name=boxKeyPairGenerateResponse,oneof"`
}
type Response_SignDetachedResponse struct {
	SignDetachedResponse *SignDetachedResponse `protobuf:"bytes,4,opt,name=signDetachedResponse,oneof"`
}
type Response_SignDetachedVerifyResponse struct {
	SignDetachedVerifyResponse *SignDetachedVerifyResponse `protobuf:"bytes,5,opt,name=signDetachedVerifyResponse,oneof"`
}
type Response_BoxEasyResponse struct {
	BoxEasyResponse *BoxEasyResponse `protobuf:"bytes,6,opt,name=boxEasyResponse,oneof"`
}
type Response_BoxEasyOpenResponse struct {
	BoxEasyOpenResponse *BoxEasyOpenResponse `protobuf:"bytes,7,opt,name=boxEasyOpenResponse,oneof"`
}
type Response_BoxSealResponse struct {
	BoxSealResponse *BoxSealResponse `protobuf:"bytes,8,opt,name=boxSealResponse,oneof"`
}
type Response_BoxSealOpenResponse struct {
	BoxSealOpenResponse *BoxSealOpenResponse `protobuf:"bytes,9,opt,name=boxSealOpenResponse,oneof"`
}
type Response_HashGenericResponse struct {
	HashGenericResponse *HashGenericResponse `protobuf:"bytes,10,opt,name=hashGenericResponse,oneof"`
}

func (*Response_Error) isResponse_SodiumResult()                       {}
func (*Response_SignKeyPairGenerateResponse) isResponse_SodiumResult() {}
func (*Response_BoxKeyPairGenerateResponse) isResponse_SodiumResult()  {}
func (*Response_SignDetachedResponse) isResponse_SodiumResult()        {}
func (*Response_SignDetachedVerifyResponse) isResponse_SodiumResult()  {}
func (*Response_BoxEasyResponse) isResponse_SodiumResult()             {}
func (*Response_BoxEasyOpenResponse) isResponse_SodiumResult()         {}
func (*Response_BoxSealResponse) isResponse_SodiumResult()             {}
func (*Response_BoxSealOpenResponse) isResponse_SodiumResult()         {}
func (*Response_HashGenericResponse) isResponse_SodiumResult()         {}

func (m *Response) GetSodiumResult() isResponse_SodiumResult {
	if m != nil {
		return m.SodiumResult
	}
	return nil
}

func (m *Response) GetError() Error {
	if x, ok := m.GetSodiumResult().(*Response_Error); ok {
		return x.Error
	}
	return Error_ERROR_UNKNOWN
}

func (m *Response) GetSignKeyPairGenerateResponse() *SignKeyPairGenerateResponse {
	if x, ok := m.GetSodiumResult().(*Response_SignKeyPairGenerateResponse); ok {
		return x.SignKeyPairGenerateResponse
	}
	return nil
}

func (m *Response) GetBoxKeyPairGenerateResponse() *BoxKeyPairGenerateResponse {
	if x, ok := m.GetSodiumResult().(*Response_BoxKeyPairGenerateResponse); ok {
		return x.BoxKeyPairGenerateResponse
	}
	return nil
}

func (m *Response) GetSignDetachedResponse() *SignDetachedResponse {
	if x, ok := m.GetSodiumResult().(*Response_SignDetachedResponse); ok {
		return x.SignDetachedResponse
	}
	return nil
}

func (m *Response) GetSignDetachedVerifyResponse() *SignDetachedVerifyResponse {
	if x, ok := m.GetSodiumResult().(*Response_SignDetachedVerifyResponse); ok {
		return x.SignDetachedVerifyResponse
	}
	return nil
}

func (m *Response) GetBoxEasyResponse() *BoxEasyResponse {
	if x, ok := m.GetSodiumResult().(*Response_BoxEasyResponse); ok {
		return x.BoxEasyResponse
	}
	return nil
}

func (m *Response) GetBoxEasyOpenResponse() *BoxEasyOpenResponse {
	if x, ok := m.GetSodiumResult().(*Response_BoxEasyOpenResponse); ok {
		return x.BoxEasyOpenResponse
	}
	return nil
}

func (m *Response) GetBoxSealResponse() *BoxSealResponse {
	if x, ok := m.GetSodiumResult().(*Response_BoxSealResponse); ok {
		return x.BoxSealResponse
	}
	return nil
}

func (m *Response) GetBoxSealOpenResponse() *BoxSealOpenResponse {
	if x, ok := m.GetSodiumResult().(*Response_BoxSealOpenResponse); ok {
		return x.BoxSealOpenResponse
	}
	return nil
}

func (m *Response) GetHashGenericResponse() *HashGenericResponse {
	if x, ok := m.GetSodiumResult().(*Response_HashGenericResponse); ok {
		return x.HashGenericResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Error)(nil),
		(*Response_SignKeyPairGenerateResponse)(nil),
		(*Response_BoxKeyPairGenerateResponse)(nil),
		(*Response_SignDetachedResponse)(nil),
		(*Response_SignDetachedVerifyResponse)(nil),
		(*Response_BoxEasyResponse)(nil),
		(*Response_BoxEasyOpenResponse)(nil),
		(*Response_BoxSealResponse)(nil),
		(*Response_BoxSealOpenResponse)(nil),
		(*Response_HashGenericResponse)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// sodium_result
	switch x := m.SodiumResult.(type) {
	case *Response_Error:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Error))
	case *Response_SignKeyPairGenerateResponse:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignKeyPairGenerateResponse); err != nil {
			return err
		}
	case *Response_BoxKeyPairGenerateResponse:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxKeyPairGenerateResponse); err != nil {
			return err
		}
	case *Response_SignDetachedResponse:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignDetachedResponse); err != nil {
			return err
		}
	case *Response_SignDetachedVerifyResponse:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SignDetachedVerifyResponse); err != nil {
			return err
		}
	case *Response_BoxEasyResponse:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxEasyResponse); err != nil {
			return err
		}
	case *Response_BoxEasyOpenResponse:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxEasyOpenResponse); err != nil {
			return err
		}
	case *Response_BoxSealResponse:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxSealResponse); err != nil {
			return err
		}
	case *Response_BoxSealOpenResponse:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoxSealOpenResponse); err != nil {
			return err
		}
	case *Response_HashGenericResponse:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HashGenericResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.SodiumResult has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // sodium_result.error
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.SodiumResult = &Response_Error{Error(x)}
		return true, err
	case 2: // sodium_result.signKeyPairGenerateResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignKeyPairGenerateResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_SignKeyPairGenerateResponse{msg}
		return true, err
	case 3: // sodium_result.boxKeyPairGenerateResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxKeyPairGenerateResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_BoxKeyPairGenerateResponse{msg}
		return true, err
	case 4: // sodium_result.signDetachedResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignDetachedResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_SignDetachedResponse{msg}
		return true, err
	case 5: // sodium_result.signDetachedVerifyResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SignDetachedVerifyResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_SignDetachedVerifyResponse{msg}
		return true, err
	case 6: // sodium_result.boxEasyResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxEasyResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_BoxEasyResponse{msg}
		return true, err
	case 7: // sodium_result.boxEasyOpenResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxEasyOpenResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_BoxEasyOpenResponse{msg}
		return true, err
	case 8: // sodium_result.boxSealResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxSealResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_BoxSealResponse{msg}
		return true, err
	case 9: // sodium_result.boxSealOpenResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoxSealOpenResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_BoxSealOpenResponse{msg}
		return true, err
	case 10: // sodium_result.hashGenericResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HashGenericResponse)
		err := b.DecodeMessage(msg)
		m.SodiumResult = &Response_HashGenericResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// sodium_result
	switch x := m.SodiumResult.(type) {
	case *Response_Error:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Error))
	case *Response_SignKeyPairGenerateResponse:
		s := proto.Size(x.SignKeyPairGenerateResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BoxKeyPairGenerateResponse:
		s := proto.Size(x.BoxKeyPairGenerateResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_SignDetachedResponse:
		s := proto.Size(x.SignDetachedResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_SignDetachedVerifyResponse:
		s := proto.Size(x.SignDetachedVerifyResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BoxEasyResponse:
		s := proto.Size(x.BoxEasyResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BoxEasyOpenResponse:
		s := proto.Size(x.BoxEasyOpenResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BoxSealResponse:
		s := proto.Size(x.BoxSealResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BoxSealOpenResponse:
		s := proto.Size(x.BoxSealOpenResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_HashGenericResponse:
		s := proto.Size(x.HashGenericResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*KeyPair)(nil), "sodium.KeyPair")
	proto.RegisterType((*SignKeyPairGenerateRequest)(nil), "sodium.SignKeyPairGenerateRequest")
	proto.RegisterType((*SignKeyPairGenerateResponse)(nil), "sodium.SignKeyPairGenerateResponse")
	proto.RegisterType((*BoxKeyPairGenerateRequest)(nil), "sodium.BoxKeyPairGenerateRequest")
	proto.RegisterType((*BoxKeyPairGenerateResponse)(nil), "sodium.BoxKeyPairGenerateResponse")
	proto.RegisterType((*SignDetachedRequest)(nil), "sodium.SignDetachedRequest")
	proto.RegisterType((*SignDetachedResponse)(nil), "sodium.SignDetachedResponse")
	proto.RegisterType((*SignDetachedVerifyRequest)(nil), "sodium.SignDetachedVerifyRequest")
	proto.RegisterType((*SignDetachedVerifyResponse)(nil), "sodium.SignDetachedVerifyResponse")
	proto.RegisterType((*BoxEasyRequest)(nil), "sodium.BoxEasyRequest")
	proto.RegisterType((*BoxEasyResponse)(nil), "sodium.BoxEasyResponse")
	proto.RegisterType((*BoxEasyOpenRequest)(nil), "sodium.BoxEasyOpenRequest")
	proto.RegisterType((*BoxEasyOpenResponse)(nil), "sodium.BoxEasyOpenResponse")
	proto.RegisterType((*BoxSealRequest)(nil), "sodium.BoxSealRequest")
	proto.RegisterType((*BoxSealResponse)(nil), "sodium.BoxSealResponse")
	proto.RegisterType((*BoxSealOpenRequest)(nil), "sodium.BoxSealOpenRequest")
	proto.RegisterType((*BoxSealOpenResponse)(nil), "sodium.BoxSealOpenResponse")
	proto.RegisterType((*HashGenericRequest)(nil), "sodium.HashGenericRequest")
	proto.RegisterType((*HashGenericResponse)(nil), "sodium.HashGenericResponse")
	proto.RegisterType((*Request)(nil), "sodium.Request")
	proto.RegisterType((*Response)(nil), "sodium.Response")
	proto.RegisterEnum("sodium.Error", Error_name, Error_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_01c5bf96341473c8) }

var fileDescriptor_protocol_01c5bf96341473c8 = []byte{
	// 870 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xef, 0x4e, 0xdb, 0x48,
	0x10, 0x77, 0xc2, 0x25, 0x81, 0xe1, 0x48, 0x72, 0x1b, 0x04, 0x4e, 0xc2, 0x9d, 0xee, 0x16, 0x9d,
	0xd4, 0xf2, 0x21, 0x52, 0xe1, 0x05, 0x4a, 0x8a, 0x8b, 0x11, 0x21, 0xa1, 0x0b, 0xb4, 0x1f, 0x23,
	0xdb, 0xd9, 0x26, 0x6e, 0x83, 0x1d, 0xbc, 0x8e, 0x04, 0x2f, 0x50, 0xf5, 0xd1, 0xfa, 0x58, 0xd5,
	0xda, 0x6b, 0xc7, 0xff, 0x09, 0x55, 0xbf, 0xc5, 0x3b, 0x33, 0xbf, 0xf9, 0xed, 0x78, 0x7e, 0x33,
	0x0e, 0xd4, 0x17, 0x8e, 0xed, 0xda, 0x86, 0x3d, 0xef, 0x79, 0x3f, 0x50, 0x95, 0xd9, 0x13, 0x73,
	0x79, 0x8f, 0x15, 0xa8, 0x5d, 0xd2, 0xa7, 0x6b, 0xcd, 0x74, 0xd0, 0x01, 0x6c, 0x2d, 0x96, 0xfa,
	0xdc, 0x34, 0x2e, 0xe9, 0x93, 0x5c, 0xfa, 0xb7, 0xf4, 0xea, 0x4f, 0xb2, 0x3a, 0xe0, 0x56, 0x46,
	0x0d, 0x87, 0xba, 0xdc, 0x5a, 0xf6, 0xad, 0xe1, 0x01, 0x3e, 0x80, 0xce, 0x8d, 0x39, 0xb5, 0x04,
	0xd4, 0x39, 0xb5, 0xa8, 0xa3, 0xb9, 0x94, 0xd0, 0x87, 0x25, 0x65, 0x2e, 0xbe, 0x87, 0x6e, 0xa6,
	0x95, 0x2d, 0x6c, 0x8b, 0x51, 0xf4, 0x1a, 0x6a, 0x5f, 0x7d, 0x93, 0x97, 0x76, 0xfb, 0xb8, 0xd1,
	0xf3, 0xd9, 0xf5, 0x44, 0x04, 0x09, 0xec, 0xe8, 0x10, 0x2a, 0xd4, 0x71, 0x6c, 0xc7, 0x63, 0x50,
	0x3f, 0xde, 0x09, 0x1c, 0x15, 0x7e, 0x48, 0x7c, 0x1b, 0xee, 0x42, 0xbb, 0x6f, 0x3f, 0xe6, 0x70,
	0x39, 0x87, 0x4e, 0x96, 0xf1, 0xc5, 0x54, 0xf0, 0x15, 0xb4, 0xf8, 0xa5, 0xce, 0xa8, 0xab, 0x19,
	0x33, 0x3a, 0x11, 0xf8, 0x48, 0x86, 0xda, 0x3d, 0x65, 0x4c, 0x9b, 0x52, 0x51, 0xc3, 0xe0, 0xf1,
	0x99, 0x0a, 0xf6, 0x60, 0x37, 0x0e, 0x27, 0x18, 0xed, 0x41, 0x75, 0x62, 0x4e, 0x29, 0x73, 0x05,
	0x9c, 0x78, 0xc2, 0x0f, 0xd0, 0x8e, 0xfa, 0x7f, 0xa4, 0x8e, 0xf9, 0xf9, 0x69, 0x2d, 0x12, 0xab,
	0x97, 0x5c, 0xce, 0x7a, 0xc9, 0xe6, 0xd4, 0xd2, 0xdc, 0xa5, 0x43, 0xe5, 0x0d, 0x41, 0x31, 0x38,
	0xc0, 0xaa, 0xff, 0x92, 0x93, 0x29, 0x05, 0xd1, 0x23, 0x68, 0x86, 0xae, 0x57, 0x9a, 0x6b, 0xcc,
	0x28, 0xf3, 0x92, 0x6f, 0x92, 0xd4, 0x39, 0xfe, 0x02, 0xf5, 0xbe, 0xfd, 0xa8, 0x68, 0x2c, 0x64,
	0xcc, 0x79, 0xcd, 0x35, 0xd3, 0x72, 0xe9, 0xa3, 0x1b, 0x36, 0x5f, 0x70, 0xb0, 0x06, 0xeb, 0xb0,
	0xb0, 0x1b, 0xc9, 0xc2, 0x9e, 0x43, 0x23, 0xcc, 0x25, 0xa8, 0xfe, 0x03, 0x60, 0x98, 0x8b, 0x19,
	0x75, 0x22, 0xd9, 0x22, 0x27, 0x68, 0x17, 0x2a, 0x96, 0x6d, 0x19, 0x54, 0xa4, 0xf2, 0x1f, 0xf0,
	0xb7, 0x12, 0x20, 0x81, 0x34, 0x5a, 0x50, 0x2b, 0x60, 0xfe, 0x4b, 0x60, 0xf1, 0x1b, 0x6d, 0x14,
	0xde, 0xe8, 0x8f, 0xe4, 0x8d, 0x4e, 0xa0, 0x15, 0xe3, 0x21, 0x6e, 0x55, 0x58, 0x42, 0x3c, 0xf0,
	0x4a, 0x7e, 0x43, 0xb5, 0xf9, 0x6f, 0x28, 0x39, 0x7e, 0xe3, 0x15, 0xd5, 0x47, 0x5b, 0xaf, 0xa8,
	0x78, 0xec, 0x55, 0x8f, 0x87, 0xbc, 0xa4, 0x7a, 0xbe, 0x20, 0x17, 0x5c, 0x90, 0xe5, 0x7c, 0x41,
	0x72, 0xbb, 0x28, 0xcb, 0x2a, 0xc1, 0x5a, 0x65, 0xe9, 0x01, 0x52, 0x35, 0x36, 0xf3, 0x06, 0x81,
	0x69, 0x3c, 0xab, 0x1f, 0x9e, 0x24, 0xe6, 0xbf, 0x4a, 0xb2, 0x12, 0x4e, 0x29, 0x29, 0x9c, 0xef,
	0x55, 0xa8, 0x05, 0xd0, 0x13, 0xe8, 0xb0, 0xdc, 0x49, 0x29, 0x86, 0x0e, 0x0e, 0xee, 0x98, 0x3f,
	0x53, 0x55, 0x89, 0x14, 0xe0, 0x20, 0x0d, 0xda, 0x7a, 0xde, 0x08, 0x14, 0x85, 0xfc, 0x2f, 0x48,
	0x92, 0x3b, 0x2b, 0x55, 0x89, 0xe4, 0xa3, 0xa0, 0x11, 0xb4, 0x58, 0x7a, 0xfe, 0x79, 0xbd, 0xbc,
	0x7d, 0xdc, 0x8d, 0xde, 0x20, 0xe1, 0xa2, 0x4a, 0x24, 0x2b, 0x92, 0x73, 0x66, 0x79, 0x13, 0xcd,
	0x13, 0x41, 0x84, 0x73, 0xee, 0xe8, 0xe3, 0x9c, 0x73, 0x51, 0xd0, 0x5b, 0xa8, 0xeb, 0xb1, 0xb9,
	0x23, 0x57, 0x3c, 0xdc, 0xbd, 0x48, 0x2d, 0x22, 0x56, 0x55, 0x22, 0x09, 0x7f, 0x34, 0x00, 0xa4,
	0xa7, 0x66, 0x80, 0x5c, 0xf5, 0x50, 0x3a, 0x09, 0x94, 0x88, 0x87, 0x2a, 0x91, 0x8c, 0x38, 0xc1,
	0x27, 0x22, 0x4a, 0xb9, 0x96, 0xe2, 0x13, 0xb1, 0x0a, 0x3e, 0x51, 0x11, 0xfb, 0x7c, 0x12, 0xaa,
	0x92, 0x37, 0x53, 0x7c, 0x12, 0x1e, 0x82, 0x4f, 0x52, 0x8d, 0x03, 0x40, 0xb3, 0x94, 0x1a, 0xe4,
	0xad, 0x38, 0x5a, 0x5a, 0x2f, 0x1c, 0x2d, 0x1d, 0xd7, 0x47, 0xd0, 0xf4, 0x43, 0xc6, 0xf6, 0x82,
	0xb7, 0x8e, 0x69, 0x5b, 0xf8, 0x47, 0x15, 0x36, 0x43, 0xd5, 0xfc, 0x1f, 0x6c, 0xf3, 0x52, 0xc6,
	0x36, 0x57, 0x25, 0xb1, 0xcf, 0xd1, 0x14, 0xba, 0x2c, 0xff, 0xf3, 0x41, 0xb4, 0xf3, 0x61, 0xa1,
	0x66, 0x7c, 0x57, 0x55, 0x22, 0x45, 0x48, 0x5c, 0x9b, 0x7a, 0xee, 0xb7, 0x81, 0xe8, 0x6c, 0x5c,
	0x24, 0x9b, 0x30, 0x4d, 0x01, 0x0e, 0x22, 0xb0, 0xcb, 0x32, 0x36, 0xbd, 0x68, 0xf1, 0x83, 0x6c,
	0xe5, 0x84, 0xc8, 0x99, 0xb1, 0xc1, 0x54, 0xc9, 0x5e, 0xcd, 0xa2, 0xc9, 0x71, 0x91, 0x78, 0x56,
	0xcc, 0xf3, 0x71, 0xd0, 0x3b, 0x68, 0xe8, 0xf1, 0x55, 0x2a, 0x3a, 0x7f, 0x3f, 0xa5, 0x9f, 0x10,
	0x2f, 0x19, 0xc1, 0xe7, 0x86, 0x9e, 0xde, 0x5e, 0xa2, 0xf1, 0xbb, 0x99, 0x12, 0x0a, 0xc1, 0xb2,
	0x22, 0x05, 0xab, 0xe8, 0x2e, 0x12, 0xfd, 0xbf, 0x9f, 0x52, 0x51, 0x8c, 0x55, 0x6c, 0x7b, 0xf9,
	0xac, 0x92, 0xcb, 0x43, 0xb4, 0x7e, 0x37, 0x53, 0x48, 0x31, 0x56, 0xa9, 0xb5, 0x33, 0x82, 0xd6,
	0x2c, 0xbd, 0x28, 0x64, 0x88, 0x03, 0x66, 0xec, 0x12, 0x0e, 0x98, 0x11, 0xd9, 0x6f, 0xc0, 0x8e,
	0x50, 0x93, 0x43, 0xd9, 0x72, 0xee, 0x1e, 0xdd, 0x41, 0xc5, 0x13, 0x0a, 0xfa, 0x0b, 0x76, 0x14,
	0x42, 0x46, 0x64, 0x7c, 0x37, 0xbc, 0x1c, 0x8e, 0x3e, 0x0d, 0x9b, 0x12, 0xea, 0xc0, 0x9e, 0x7f,
	0x34, 0xba, 0x56, 0xc8, 0xe9, 0xed, 0xc5, 0x68, 0x38, 0x7e, 0x7f, 0x7a, 0x31, 0x50, 0xce, 0x9a,
	0x25, 0xf4, 0x37, 0xb4, 0x7d, 0x1b, 0x51, 0x4e, 0xcf, 0xc6, 0x44, 0xf9, 0x70, 0xa7, 0xdc, 0xdc,
	0x06, 0xe6, 0xb2, 0x5e, 0xf5, 0xfe, 0x20, 0x9c, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xff,
	0xcd, 0x80, 0x32, 0x0c, 0x00, 0x00,
}
